





server:
  port: 8888
  
spring:
  application:
    name: CONFIG-APP
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hardcoader/cloudconfigserver
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
